---
kind: Service
apiVersion: v1
metadata:
  name: automosmobile
spec:
  selector:
    app: automos
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 80
      nodePort: 30002
  type: LoadBalancer
 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: automos
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: automos
    spec:
      containers:
        - name: automos
          image: mihalceamihai/apache
          ports:
            - containerPort: 8080
          env:
          - name: MYSQL_HOST
            value: "db"
          - name: MYSQL_USER
            value: "mosu"
          - name: MYSQL_PASS
            value: "123"
          - name: MYSQL_DB
            value: "automosmobile"

---
kind: Service
apiVersion: v1
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
    - protocol: "TCP"
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: db
spec:
  containers:
    - name: db
      image: mihalceamihai/mysql
      ports:
        - containerPort: 3306
